<a href="https://colab.research.google.com/github/vcdemy/20220726-cht/blob/main/20220728.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 20220728

## 複習一下

四個基礎的資料型態:
* int
* float
* bool
* str

四個基礎的容器型別：
* list
* tuple
* dict
* set

四個基礎的語法：
* 條件式 (if)
  * 選擇性的執行程式區塊
* 迴圈 (loops)
  * 反覆執行程式區塊
* 函式 (functions)
  * 先定義好程式區塊，呼叫的時候再執行
* 例外處理 (Exception Handling)
  * 嘗試執行某個程式區塊，如果發生錯誤，呼叫另外一個程式區塊來處理錯誤

## 條件式 (if statements)

In [2]:
a = 1
b = 2

if a > b:
  print("a 大於 b")

In [5]:
a = 1
b = 2

if a > b:
  print("a 大於 b")
else:
  print("a 沒有大於 b")

a 沒有大於 b


In [6]:
a = 2
b = 2

if a > b:
  print("a 大於 b")
elif a < b: # elif ==> else if
  print("a 小於 b")
else:
  print("a 等於 b")

a 等於 b


### 練習：

$ bmi = \frac{體重(公斤)}{身高(公尺)^2} $

|bmi|說明|
|:-:|:-:|
|bmi < 18 | 過輕|
|18 < bmi < 24 | 健康|
|bmi > 24 | 過重|

In [7]:
w = 80
h = 1.83
bmi = w / h**2

In [8]:
bmi

23.888440980620498

In [9]:
if bmi < 18:
  print("過輕")
elif bmi > 24:
  print("過重")
else:
  print("健康")

健康


In [12]:
def health(w, h):
  bmi = w / h**2
  if bmi < 18:
    print("過輕")
  elif bmi > 24:
    print("過重")
  else:
    print("健康")

In [13]:
health(80, 1.83)

健康


In [16]:
def health(w, h):
  bmi = w / h**2
  if bmi < 18:
    return "過輕"
  elif bmi > 24:
    return "過重"
  else:
    return "健康"

In [17]:
health(80, 1.83)

'健康'

In [18]:
x = health(80, 1.83)

In [19]:
x

'健康'

## 迴圈 (loops)

* for
* while

In [20]:
for i in range(5):
  print(i)

0
1
2
3
4


In [22]:
for i in range(5):
  print(2*i+1)

1
3
5
7
9


In [23]:
"*" + " " + "*"

'* *'

In [24]:
"*" * 5

'*****'

In [26]:
for i in range(5):
  print((2*i+1)*"*")

*
***
*****
*******
*********


In [28]:
for i in range(5):
  print((5-i)*" "+(2*i+1)*"*")

     *
    ***
   *****
  *******
 *********


## 函式 (functions)

In [34]:
def pyramid(h):
  for i in range(h):
    print((h-i)*" "+(2*i+1)*"*")

In [36]:
pyramid(10)

          *
         ***
        *****
       *******
      *********
     ***********
    *************
   ***************
  *****************
 *******************


### 關於程式區塊

In [38]:
for i in range(3):
  print("開始")
  print(i)
  print("結束")

開始
0
結束
開始
1
結束
開始
2
結束


In [39]:
for i in range(3):
  print("開始")
  print(i)
print("結束")

開始
0
開始
1
開始
2
結束


### 關於for迴圈

In [40]:
for i in range(5):
  print(i)

0
1
2
3
4


In [41]:
x = list("abcde")

In [42]:
x

['a', 'b', 'c', 'd', 'e']

In [44]:
for i in x:
  print(i)

a
b
c
d
e


In [45]:
y = {"apple":10, "orange":20, "banana":30}

In [46]:
for i in y:
  print(i)

apple
orange
banana


In [47]:
for i in y.items():
  print(i)

('apple', 10)
('orange', 20)
('banana', 30)


In [48]:
for i in y:
  print(i, "==>", y[i])

apple ==> 10
orange ==> 20
banana ==> 30


## 例外處理 (Exception Handling)

### f-string

In [50]:
x = 1
y = 2
print(x, "adadfda" ,y)

1 adadfda 2


In [51]:
print(f"x = {x}, y = {y}")

x = 1, y = 2


In [52]:
def add(x, y):
  print(f"{x} + {y} = {x+y}")

In [53]:
add(1, 2)

1 + 2 = 3


In [54]:
def add(x, y):
  print(f"{x} + {y} = {x+y}")

def sub(x, y):
  print(f"{x} - {y} = {x-y}")

def mul(x, y):
  print(f"{x} x {y} = {x*y}")

def div(x, y):
  print(f"{x} / {y} = {x/y}")

In [55]:
funcs = [add, div, sub, mul]

In [56]:
x = 1
y = 2
for func in funcs:
  func(x, y)

1 + 2 = 3
1 / 2 = 0.5
1 - 2 = -1
1 x 2 = 2


In [57]:
x = 1
y = 0
for func in funcs:
  func(x, y)

1 + 0 = 1


ZeroDivisionError: ignored

In [58]:
x = 1
y = 0
for func in funcs:
  try:
    func(x, y)
  except Exception as e:
    print(e.args)

1 + 0 = 1
('division by zero',)
1 - 0 = 1
1 x 0 = 0


## 資料分析簡介

* Numpy => Numerical Python => 科學運算套件
* MatPlotLib => Matrix Plotting Library => 繪圖基礎套件
* Pandas => Panel Data => 資料分析基礎套件

套件載入的慣用法：

```python
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
```

## Numpy

* ndarray => N-Dimensional Arrays
* ufunc => Universal Functions

### why ndarrays?

In [59]:
import numpy as np

In [60]:
x = [1, 2, 3]
y = [4, 5, 6]

In [61]:
x + y

[1, 2, 3, 4, 5, 6]

In [62]:
2 * x

[1, 2, 3, 1, 2, 3]

In [65]:
list(zip(x, y))

[(1, 4), (2, 5), (3, 6)]

In [63]:
z = []
for i, j in zip(x, y):
  z.append(i+j)

In [64]:
z

[5, 7, 9]

In [66]:
z.append?

In [67]:
x1 = np.array(x)
y1 = np.array(y)

In [68]:
x1

array([1, 2, 3])

In [69]:
y1

array([4, 5, 6])

In [70]:
x1 + y1

array([5, 7, 9])

In [71]:
2 * x1

array([2, 4, 6])

### What is ufunc?

In [72]:
import math

In [73]:
math.sin(math.pi/2)

1.0

In [74]:
math.sin(x)

TypeError: ignored

In [75]:
np.sin(np.pi/2)

1.0

In [76]:
np.sin(x)

array([0.84147098, 0.90929743, 0.14112001])

### 練習:

請將底下所有資料取根號(np.sqrt)再乘上十。

In [77]:
data = np.random.randint(20, 70, 10)

In [78]:
data

array([33, 32, 69, 34, 30, 30, 33, 42, 48, 65])

In [80]:
for i in data:
  print(math.sqrt(i)*10)

57.445626465380286
56.568542494923804
83.06623862918075
58.309518948453004
54.772255750516614
54.772255750516614
57.445626465380286
64.8074069840786
69.28203230275508
80.62257748298549


In [81]:
np.sqrt(data)*10

array([57.44562647, 56.56854249, 83.06623863, 58.30951895, 54.77225575,
       54.77225575, 57.44562647, 64.80740698, 69.2820323 , 80.62257748])

### ndarray的indexing跟slicing

In [82]:
list(range(25))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24]

In [83]:
x = np.arange(25)

In [84]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [85]:
x.dtype

dtype('int64')

In [86]:
x.shape

(25,)

In [87]:
x.size

25

In [91]:
x = x.reshape(5, 5)

In [92]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [93]:
x.shape

(5, 5)

In [96]:
y = [[ 0,  1,  2,  3,  4],
     [ 5,  6,  7,  8,  9],
     [10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19],
     [20, 21, 22, 23, 24]]

In [101]:
y[2][2]

12

In [102]:
x[2][2]

12

In [104]:
y[2][1:4]

[11, 12, 13]

In [105]:
x[2][1:4]

array([11, 12, 13])

In [106]:
# ndarray的indexing
x[2, 2]

12

In [112]:
# ndarray的slicing
x[2, 1:4]

array([11, 12, 13])

In [108]:
x[1:3, 1:3]

array([[ 6,  7],
       [11, 12]])

In [109]:
# 取得第零列 x[0]
x[0, :]

array([0, 1, 2, 3, 4])

In [111]:
# 取得第零欄
x[:, 0]

array([ 0,  5, 10, 15, 20])